### ISSUE TITLE
CodeIgniter Organization

### ISSUE THREAD

**Issue by MGatner** [CodeIgniter/codeigniter.github.io#1]
Hello @hex-ci - This is MGatner from the CodeIgniter team. We would be interested in using this organization (https://github.com/CodeIgniter) for official Foundation projects. Would you be willing to transfer it?

If you would like to discuss more please come on the official CodeIgniter Slack or Forums and you can send me a private message.

**Comment by MGatner** [comment]
Thank you, that is very kind! I am also happy to hear how you have been maintaining the Chinese community. Our forums and Slack are woefully stuck in English but I would be very happy to have more international connections wherever we can work out the language barrier. I work mostly in version 4, but if you ever have any questions from the Chinese community you want to forward I will happily receive them. 

For the transfer, I think the best approach would be to make Lonnie (@lonnieezell) the owner of the organization. He is the lead member of the CodeIgniter Foundation and can make sure it gets established correctly. Thank you again for your interest in helping!

**Comment by lonnieezell** [comment]
@hex-ci Thank you very much for inviting me. I've gladly accepted the invitation.  Thank you so much for being open to transferring this. That is awesome! This will help to make our repos much less confusing as the project continues to grow. 

We are definitely happy to work with you however we can. We are a pretty small team, but let us know if you have any ideas how we can work more closely together.
